name: Report a bug
description: Tell us about a bug or issue you may have identified in this library.
title: 'Provide a general summary of the issue'
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please take a couple of minutes to help me work faster.
      options:
        - label: I have read the [contributing guidelines](https://github.com/Proskynete/vertical-timeline-component-react/blob/master/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
  - type: input
    id: version
    attributes:
      label: What version of this library are you using?
      placeholder: 'e.g., v3.0.4 or v2.1.2'
    validations:
      required: true
