contact_links:
  - name: Ask the community
    url: https://github.com/Proskynete/vertical-timeline-component-react/discussions/new
    about: Ask and discuss questions with other members of the community.
