name: Feature request
description: Suggest new or updated features to include the library.
title: 'Suggest a new feature'
labels: [feature]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please take a couple of minutes to help me work faster.
      options:
        - label: I have [searched](https://github.com/Proskynete/vertical-timeline-component-react/issues?q=is%3Aissue) for duplicate or closed feature requests
          required: true
        - label: I have read the [contributing guidelines](https://github.com/Proskynete/vertical-timeline-component-react/blob/master/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Please provide detailed information on what we should add.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation and context
      description: Tell us why this change is needed or helpful, and what problems it may help solve.
    validations:
      required: true
